develop: docker migration to php 8.1
alextselegidis/easyappointments pull request #1358
Opened 2023-04-30 01:06 UTC by fliot

2023-05-02 07:28 UTC, alextselegidis commented
Hello! 

Thanks for this PR, I'll review and get back to you. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

2023-06-03 07:41 UTC, alextselegidis commented
Thanks for the great proposals! I've posted a couple of questions for you to check. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

2023-06-07 13:42 UTC, fliot commented
Hi @alextselegidis,
I don't see any comment or question, anywhere.
Not able to review or answer them.
Let me know your thoughs.
Regards.

2023-06-12 10:46 UTC, alextselegidis commented
Hi @fliot 

Aren't the following review comments visible to you? 

![image](https://github.com/alextselegidis/easyappointments/assets/4527441/1c681796-0b77-4ab3-962b-c5130088ca61)

2023-06-13 09:06 UTC, fahim44 commented
@alextselegidis your comments are in the pending state. You should find a submit button below.

2023-06-14 13:32 UTC, fliot commented
Hi @alextselegidis ,
I confirm, I do not see yet your comments,
You probably have to submit them, as described by @fahim44 
Thanks in advance.

2023-06-19 09:53 UTC, alextselegidis requested changes

2023-06-19 09:53 UTC, alextselegidis commented
Thanks, that was it indeed 👍 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

2023-06-20 09:09 UTC, fliot commented on docker/php-fpm/Dockerfile
> +RUN apt-get -y autoremove \
Lighter result, just removing 100 Mb to the final image.

2023-06-20 09:29 UTC, fliot commented on application/config/routes.php
> +| The accepted 3rd party websites, for which CORS must be configured,
Several points,
1) your default proposal (before my patch) allows "*" for cors, so for most of usage, it's an immediate working configuration, but it's clearly unsecure
2) your initial code wasn't perfectly working with HEAD (which is used by many javascript rest implementation)
3) your initial code wasn't reporting allow-credentials and allow-headers directives (see docker/nginx/nginx.conf) which is also for many javascript implementation a real issue.

So, about a default configuration,
I fully agree with you, most users won't be able to handle this by-themselves.
The cleanest way to handle this, is to keep track of this in the database, and authorize backend users to configure cors authorized domains directly.

Only "origin" must be configurable, other headers must be hardcoded :
Access-Control-Allow-Origin $http_origin # with default value "*" to not break compatibility
Access-Control-Allow-Credentials "true"
Access-Control-Allow-Methods "GET,POST,PUT,PATCH,DELETE,HEAD,OPTIONS"
Access-Control-Allow-Headers "Authorization, Access-Control-Allow-Headers, Origin, Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers"

2023-07-03 08:11 UTC, alextselegidis commented
Hello! 

Quick update on this PR, there are some parts that I would definitely like to add to the current set up. 

The manual merge will take place soon. 

Thanks for the great work!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

2023-08-02 17:10 UTC, alextselegidis commented on application/config/routes.php
> +| The accepted 3rd party websites, for which CORS must be configured,
Thanks for all the clarifications, I really appreciate them. 

For now and in order to keep things as simple as possible for the most people, I will keep the inline CORS configuration and document in the updated developers docs (will be published soon). 

I will not make this a setting yet, most likely will do so in the future.

2023-08-02 17:10 UTC, alextselegidis commented
Hello! 

I have now migrated all the parts that I'd like to have in the developer docker-compose setup. 

Thanks for this PR! 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

2023-08-02 17:10 UTC, closed without merging